### Create student account
POST http://localhost:3000/api/account_creation_form
Content-Type: application/json; charset=utf-8

{
    "username":"student_test",
    "email":"n01413497@unf.edu",
    "password":"king",
    "role": "student"
}

### Create faculty account
POST http://localhost:3000/api/account_creation_form
Content-Type: application/json; charset=utf-8

{
    "username":"faculty_test",
    "email":"n01413497@unf.edu",
    "password":"king",
    "role": "faculty"
}

### Create admin account
POST http://localhost:3000/api/account_creation_form
Content-Type: application/json; charset=utf-8

{
    "username":"admin_test",
    "email":"n01413497@unf.edu",
    "password":"king",
    "role": "admin"
}