### Create student account
POST http://localhost:3000/api/account_creation_form
Content-Type: application/json; charset=utf-8

{
    "username":"alex_student3",
    "email":"n01413497@unf.edu",
    "password":"king",
    "role": "student"
}

### Create faculty account
POST http://localhost:3000/api/account_creation_form
Content-Type: application/json; charset=utf-8

{
    "username":"alex_faculty2",
    "email":"n01413497@unf.edu",
    "password":"king",
    "role": "faculty"
}

### Create admin account
POST http://localhost:3000/api/account_creation_form
Content-Type: application/json; charset=utf-8

{
    "username":"alex_admin",
    "email":"n01413497@unf.edu",
    "password":"king",
    "role": "admin"
}