import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/admin.module.css'
import unfLogo from '../public/UNF_Logo.gif'
import {useEffect, useState} from "react";
/*from Chance, this is where the admin will settle account requests for admin account and faculty account requests


*/






export default function Home() {
    const [dataResponse, setdataResponse] = useState([]);

  const ApproveAccount = async (data) => {
    const JSONdata = JSON.stringify(data);
    const endpoint = '/api/approve_account';
    const options = {
      // The method is POST because we are sending data.
      method: 'POST',
      // Tell the server we're sending JSON.
      headers: {
          'Content-Type': 'application/json',
      },
      // Body of the request is the JSON data we created above.
      body: JSONdata,
  }
  const response = await fetch(endpoint, options)
  const result = await response.json()
  alert("Account request has been Approved!");
  window.location.reload();
  }

  const DenyAccount = async (data) => {
    const JSONdata = JSON.stringify(data);
    const endpoint = '/api/approve_account';
    const options = {
      // The method is POST because we are sending data.
      method: 'POST',
      // Tell the server we're sending JSON.
      headers: {
          'Content-Type': 'application/json',
      },
      // Body of the request is the JSON data we created above.
      body: JSONdata,
  }
  const response = await fetch(endpoint, options)
  const result = await response.json()
  alert("Account request has been declined!");
  window.location.reload();
  }



    useEffect(() => {
      async function getPageData() {
        const apiURLEndpoint = '/api/account_request_pull';
        const response = await fetch(apiURLEndpoint);
        const res = await response.json();
        console.log(res);
      setdataResponse(res.accounts);
      }
    
    getPageData();
    }, []);
      return (
        <div className={styles.container}>
      <Head>
        <title>AdminHomepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
                <Image src={unfLogo} alt="UNF"/>
            </header>
      <main className={styles.main}>
        <h1 className={styles.title}>
        Faculty and Admin Account Requests
        </h1>

        <table className={styles.table} id="tableID">
    <thead className={styles.head}>
  <tr>
  <th className={styles.thead}>Account ID</th>
  <th className={styles.thead}>Role</th>
  <th className={styles.thead}>First Name</th>
    <th className={styles.thead}>Last Name</th>
    <th className={styles.thead}>UserName</th>
    <th className={styles.thead}>Password</th>
    <th className={styles.thead}>Email</th>
    <th className={styles.thead}>Account Status</th>
  </tr>
  </thead>
  </table>

  {dataResponse.map((account) => {
  return (
<div key={account.account_id}>
  <tbody>
<tr className={styles.trow}>
<td className={styles.tbody}>{account.account_id}</td>
<td className={styles.tbody}>{account.role}</td>
<td className={styles.tbody}>{account.first_name}</td>
<td className={styles.tbody}>{account.last_name}</td>
<td className={styles.tbody}>{account.username}</td>
<td className={styles.tbody}>{account.password}</td>
<td className={styles.tbody}>{account.email_address}</td>
<td className={styles.tbody}>{account.account_status}
<button onClick={()=>ApproveAccount(account.account_id)}>Approve</button>
<button onClick={()=>DenyAccount(account.account_id)}>Deny</button>
</td>
</tr>
</tbody>
</div>
  );
})}

</main>
</div>
    )
}

