import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/admin.module.css'
import unfLogo from '../public/UNF_Logo.gif'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>AdminHomepage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <Image src={unfLogo} alt="UNF"/>
            </header>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome</h1>

                <ul className={styles.nav}>
                    <li className={styles.nava}><Link href="/account_requests"><a className={styles.navb}>Account Requests</a></Link></li>
                    <li className={styles.nava}><Link href="/report"><a className={styles.navb}>View Reports</a></Link></li>
                    <li className={styles.nava}><Link href="/adminAccount"><a className={styles.navb}>View Accounts</a></Link></li> 
                </ul>
            </main>
        </div>
    )
}

