import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import unfLogo from '../public/UNF_Logo.gif'

export default function Home() {

    const logout = async () => {
        const response = await fetch('/api/logout', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            }
        });
        Router.push("/");
    }


    

    return (
        <div>
            <Head>
                <title>AdminHomepage</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className={styles.header}>
                <Link href="/home"><Image className={styles.image} src={unfLogo} alt="UNF"/></Link>
                <span className={styles.headerContent}>
                    {/* Removed old links, they were not needed for production */}
                    <button type="button" className={styles.headerButton} onClick={logout}>Logout</button>
                </span>
            </header>

            <main className={styles.main}>
                <h1 className={styles.title}>Welcome</h1>
                <div>
                    <Link href="/account_requests">
                    <button className={styles.approveButton}>Account Requests</button>
                    </Link>
                </div>
                   <br></br>

                <div>
                    <Link href="/reports">
                    <button className={styles.approveButton}>View Reports</button>
                    </Link>
                </div>
                <br></br>

                <div>
                    <Link href="/adminAccount">
                    <button className={styles.approveButton}>View Accounts</button>
                    </Link>
                </div>
                <br></br>


              
            </main>
        </div>
    )
}

