import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/faculty.module.css'

import unfLogo from '../public/UNF_Logo.gif'
import Link from 'next/link'



/*Reports Page
Shows unresolved reports
*/



export default function Home() {
    return (
<div className={styles.container}>
      <Head>
        <title>Faculty Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
    
      <Image className={styles.logo} src={unfLogo} alt="UNF"/>


<div className={styles.link}> 
<Link href="/faculty_homepage">Notifications &nbsp; &nbsp; </Link>

<Link href="/settings">Settings</Link>
</div>




      <main className={styles.main}>

<h1> 
  FACULTY HOMEPAGE
</h1>
<h3 className={styles.title}>
Student Submitted Forms
</h3>

      <ol className={styles.nav}>
            <li className={styles.nava}><a className={styles.navb} href="facultyFormQueue">View Queue</a></li>
      </ol>


</main>
</div>
    )
}