import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/faculty.module.css'
/*Reports Viewer
will load report information
*/
let Approve = "Approve"
let Deny = "Deny"
export default function Home() {
    return (
<div className={styles.container}>
      <Head>
        <title>Submitted Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

<h1 className={styles.title}>
Student Form 
</h1>

<table className={styles.tableHead}>
    <thead>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>UserName</th>
        <th>Password</th>
        <th>Leadership Event</th>
        <th>Hours Logged</th>
        <th>Sponsoring Faculty</th>
        <th>Link to Account</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>Sophia</td>
         <td>Abuzeni</td>
        <td>n01406901@unf.edu</td>
        <td>sophiaabuzeni</td>
        <td>InfoSci</td>
        <td>UNF Leaders Convention</td>
        <td>15</td>
        <td>Karthikeyen Umapathy</td>
        <td><a href="">View Student Account</a></td>
    </tr>
    </tbody>
</table>

<form className={styles.description}>
          <input type="radio" id="appr" name="store" value={Approve}/>
          <label for="appr">Approve</label>
          <br></br>
          <input type="radio" id="denied" name="store" value={Deny}/>
          <label for="denied">Deny</label>
          <br></br>
          <input type="submit" value="Submit"/>
        </form>



</main>
</div>
    )
}