import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/admin.module.css'
/*Reports Page
Shows unresolved reports
*/
export default function Home() {
    return (
<div className={styles.container}>
      <Head>
        <title>AdminReports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

<h1 className={styles.title}>
View Reports
</h1>

      <ol className={styles.nav}>
            <li className={styles.nava}><a className={styles.navb} href="reportViewer">Student Report 14/09/2022</a></li>
            <li className={styles.nava}><a className={styles.navb} href="">Student Report 15/09/2022</a></li>
            <li className={styles.nava}><a className={styles.navb} href="">Student Report 27/09/2022</a></li>
        </ol>


</main>
</div>
    )
}