import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/admin.module.css'
import unfLogo from '../public/UNF_Logo.gif'
import {useEffect, useState} from "react";
/*Reports Page
Shows unresolved reports


*/

function exportTableToExcel(tableID, filename = ''){
  var downloadLink;
  var dataType = 'application/vnd.ms-excel';
  var tableSelect = document.getElementById(tableID);
  var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
  
  // Specify file name
  filename = filename?filename+'.xls':'excel_data.xls';
  
  // Create download link element
  downloadLink = document.createElement("a");
  
  document.body.appendChild(downloadLink);
  
  if(navigator.msSaveOrOpenBlob){
      var blob = new Blob(['\ufeff', tableHTML], {
          type: dataType
      });
      navigator.msSaveOrOpenBlob( blob, filename);
  }else{
      // Create a link to the file
      downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
  
      // Setting the file name
      downloadLink.download = filename;
      
      //triggering the function
      downloadLink.click();
  }
}

export default function Home() {
  const [query, setQuery] = useState("")
  const [dataResponse, setdataResponse] = useState([]);


 

useEffect(() => {
  async function getPageData() {
    const response = await fetch('/api/entry_pull');
    const res = await response.json();
    console.log(res);
  setdataResponse(res.accounts);
  }

getPageData();
}, []);



  return (
<div className={styles.container}>
      <Head>
        <title>AdminReports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
                <Image src={unfLogo} alt="UNF"/>
            </header>
      <main className={styles.main}>
<h1 className={styles.title}>
View Reports
</h1>
<input type="text" id="input"  placeholder="Search for reports" className="search-input" data-table="reports-list" onChange={event => setQuery(event.target.value)}></input>
<button onClick={()=>exportTableToExcel("tableID")}>Excel</button>
<table className={styles.table} id="tableID">
    <thead className={styles.head}>
  <tr>
  <th className={styles.thead}>Entry ID</th>
  <th className={styles.thead}>Student ID</th>
  <th className={styles.thead}>Faculty ID</th>
    <th className={styles.thead}>Event Name</th>
    <th className={styles.thead}>Event Date</th>
    <th className={styles.thead}>Time Accrued</th>
    <th className={styles.thead}>Latest Comment</th>
    <th className={styles.thead}>Comment ID</th>
    <th className={styles.thead}>Entry Status</th>
    <th className={styles.thead}>Semester</th>
  </tr>
  </thead>
  </table>

  {
  dataResponse.filter(account => {
    if (query === '') {
      return account;
    } 
    if (account.latest_comment.toLowerCase().includes(query.toLowerCase())) {
      return account;
    }
    if (account.event_name.toLowerCase().includes(query.toLowerCase())) {
      return account;
    }
    if (account.entry_id.toString().includes(query.toLowerCase())) {
      return account;
    }
    if (account.student_id.toString().includes(query.toLowerCase())) {
      return account;
    }
    if (account.faculty_id.toString().includes(query.toLowerCase())) {
      return account;
    }
    if (account.event_date.toString().includes(query.toLowerCase())) {
      return account;
    }
    }).map((account) => {
  return (
<div key={account.entry_id}>
  <tbody>
<tr className={styles.trow}>
<td className={styles.tbody}>{account.entry_id}</td>
<td className={styles.tbody}>{account.student_id}</td>
<td className={styles.tbody}>{account.faculty_id}</td>
<td className={styles.tbody}>{account.event_name}</td>
<td className={styles.tbody}>{account.event_date}</td>
<td className={styles.tbody}>{account.time_accrued}</td>
<td className={styles.tbody}>{account.latest_comment}</td>
<td className={styles.tbody}>{account.latest_commentor_id}</td>
<td className={styles.tbody}>{account.entry_status}</td> 
<td className={styles.tbody}>{account.Semester}</td>
<td className={styles.tbody}>{}</td>
</tr>
</tbody>
</div>
  );
})}

</main>
</div>
    )
  }
    
  
