import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/admin.module.css'
/*Reports Viewer
will load report information
*/
let Approve = "Approve"
let Deny = "Deny"
export default function Home() {
    return (
<div className={styles.container}>
      <Head>
        <title>AdminReports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

<h1 className={styles.title}>
Student Report (Insert Report ID)
14/09/22
</h1>

<table className={styles.tableHead}>
    <thead>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>UserName</th>
        <th>Password</th>
        <th>Leadership Event</th>
        <th>Hours Logged</th>
        <th>Sponsoring Faculty</th>
        <th>Link to Account</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>John</td>
         <td>Doe</td>
        <td>n111111@unf.edu</td>
        <td>JohnisAwesome</td>
        <td>11111111</td>
        <td>UNF Leaders Celebration</td>
        <td>3</td>
        <td>Dr.Jane</td>
        <td><a href="">View Student Account</a></td>
    </tr>
    </tbody>
</table>

<form className={styles.description}>
          <input type="radio" id="appr" name="store" value={Approve}/>
          <label for="appr">Approve</label>
          <br></br>
          <input type="radio" id="denied" name="store" value={Deny}/>
          <label for="denied">Deny</label>
          <br></br>
          <input type="submit" value="Submit"/>
        </form>



</main>
</div>
    )
}