import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/students.module.css'
// for form input information 
import {useState} from 'react'
 
// the new student page - started over 



export default function Home() {


    // // use the useState hook to store the form data
    // const [Form, setForm] = useState({
    //   First_Name: '',
    //   Last_Name: '',
    //   email: '',
    //   notes: '',
    //   professor: 'Unknown',
    //   event: '',
    //   hours: '',
    // });


    

    // // handle the form input change
    // const onChange = (e) => {
    //   const { value, name } = e.target;

    //   setForm(state => ({
    //     ...state,
    //     [name]: value,
    //   }));
    // }

    // const showData = () => {
    //   console.log('Form: ', Form);
      
    // }


    const handleSubmit = async (event) => {
        event.preventDefault();

        const response = await fetch('/api/student_form_submit', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                selected_professor: event.target.professor.value,
                event_name: event.target.event.value,
                // event_date: event.target.password.value,
                hours_submitted: event.target.hours.value,
                latest_comment: event.target.notes.value
            }),
        });

        const result = await response.json();

        if (response.status == 200) {
            Router.push("/email_verification");
        }
        else if (response.status == 400) {
            alert(result.message);
        }
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Student - Page</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* the unf header - use the basic style */}
            <header className={styles.header}> 
                <Image className={styles.logo} src="/UNF_Logo.gif" alt="UNF" width={100} height={100}/>
                <div className={styles.link}>
                    <span className={styles.links}>
                     <Link href="/settings">Noti</Link>
                        <Link href="/settings">Settings</Link>
                    </span>
                </div> 
            </header>

            <main className={styles.main}>

                <div className={styles.student_form}>
                    <form onSubmit={handleSubmit} className={styles.form_element}>
            
                        <label className={styles.form_label}>Event:</label>
                        <input className={styles.form_input} type="text" name="event" id="left_form"/>
                        <br></br>

                        {/* <label className={styles.form_label}>Email:</label>
                        <input onChange={onChange} className={styles.form_input} type="text" name="email" id="left_form" value={Form.email}/>
                        <br></br> */}

                        <div className={styles.right_form}>
                            <label htmlFor="quantity">Hours Amount:</label>
                            <input className={styles.form_input} type="number" id="quantity" name="hours" min="1" max="100" />
                            <br></br>

                            <div className={styles.right_form}>

                                <label htmlFor="event_date">Event Date:</label>
                                <input className={styles.form_input} type="date" id="date" name="event_date"/>
                                <br></br>

                                <label htmlFor="text">Professor:</label>
                                <select className={styles.form_input} name="professor" id="professor">
                                    <option value="Karthikeyan Umapathy">Professor#1</option>
                                    <option value="Katie Tarnowska">Professor#2</option>
                                    <option value="David Wisnosky">Professor#3</option>
                                    <option value="Professor#4">Professor#4</option>
                                    <option value="Unknown">Unknown</option>
                                </select>
                                <br></br>

                                <label className={styles.form_label}>Notes:</label>
                                <textarea className={styles.form_input} type="text" name="notes" id="left_form"></textarea>
                                <br></br>

                                <div className={styles.btn_container}>
                                    <button className={styles.form_btn}>Submit</button>
                                    <button className={styles.form_btn1}>Clear</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>

            
                <div className={styles.queue}> 
                    <h3 className={styles.queue_text}>Queue:</h3>
                    <div className={styles.queue_container}>
                        <a href='#' className={styles.link_text}>Fall20</a>
                        <a href='#' className={styles.link_text1}>Sp21</a>
                        <a href='#' className={styles.link_text}>Su20</a>
                        <a href='#' className={styles.link_text1}>Fall19</a>
                        <a href='#' className={styles.link_text}>Su19</a>
                        <a href='#' className={styles.link_text1}>Fall21</a>
                        <a href='#' className={styles.link_text}>Sp22</a>
                        <a href='#' className={styles.link_text1}>Su21</a>
                        <a href='#' className={styles.link_text}>Fall22</a>
                        <a href='#' className={styles.link_text}>Sp23</a>
                    </div>
                </div>
            </main>
        </div>
    )
}

