# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - UNF-SoC-Honors-in-Computing-Hours-Tracking

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:

      # https://github.com/actions/checkout
      - name: 'Checkout Github Action' 
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: 'npm install and build'
        run: |
          npm install
          npm run build

      # https://github.com/Azure/webapps-deploy
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-versioned-actions
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        env:
          AZ-PUBLISH-PROFILE: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        with:
          app-name: 'UNF-SoC-Honors-in-Computing-Hours-Tracking'
          slot-name: 'Production'
          publish-profile: ${{ env.AZ-PUBLISH-PROFILE }}
